import validGuessesData from './validGuesses.json'

export const WORD_LIST: string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
  'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'armor', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'awake',
  'award', 'aware', 'badly', 'baker', 'bases', 'basic', 'beach', 'began', 'begin', 'being',
  'below', 'bench', 'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blind', 'block',
  'blood', 'board', 'boost', 'booth', 'bound', 'brain', 'brand', 'bread', 'break', 'breed',
  'brick', 'brief', 'bring', 'broad', 'broke', 'brown', 'brush', 'build', 'built', 'bunch',
  'burst', 'cabin', 'cable', 'calm', 'camera', 'camp', 'canal', 'candy', 'carry', 'catch',
  'cause', 'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check', 'chest',
  'chief', 'child', 'civil', 'claim', 'class', 'clean', 'clear', 'climb', 'clock', 'close',
  'cloud', 'coach', 'coast', 'could', 'count', 'court', 'cover', 'craft', 'crash', 'crazy',
  'cream', 'crime', 'cross', 'crowd', 'crown', 'crowd', 'curve', 'cycle', 'daily', 'dance',
  'dealt', 'death', 'debut', 'delay', 'depth', 'dirty', 'doubt', 'dozen', 'draft', 'drama',
  'drawn', 'dream', 'dress', 'drill', 'drink', 'drive', 'drove', 'eager', 'early', 'earth',
  'eight', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event',
  'every', 'exact', 'exist', 'extra', 'faith', 'false', 'fault', 'fiber', 'field', 'fifth',
  'fifty', 'fight', 'final', 'first', 'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus',
  'force', 'forth', 'forty', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front',
  'fruit', 'fully', 'funny', 'giant', 'given', 'glass', 'globe', 'glory', 'going', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grass', 'great', 'green', 'gross', 'group', 'grown',
  'guard', 'guess', 'guest', 'guide', 'happy', 'harsh', 'heart', 'heavy', 'hence', 'horse',
  'hotel', 'house', 'human', 'ideal', 'image', 'index', 'inner', 'input', 'issue', 'japan',
  'joint', 'judge', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'least', 'leave', 'legal', 'level', 'light', 'limit', 'lobby', 'local', 'logic', 'loose',
  'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'match', 'maybe',
  'mayor', 'medal', 'media', 'metal', 'meter', 'might', 'minor', 'minus', 'mixed', 'model',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'night',
  'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'order',
  'organ', 'other', 'ought', 'outer', 'owner', 'panel', 'panic', 'paper', 'party', 'peace',
  'phase', 'phone', 'photo', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant',
  'plate', 'point', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior',
  'prize', 'proof', 'proud', 'prove', 'pulse', 'punch', 'pupil', 'queen', 'quick', 'quiet',
  'quite', 'radio', 'raise', 'range', 'rapid', 'reach', 'react', 'ready', 'realm', 'rebel',
  'refer', 'relax', 'reply', 'right', 'rigid', 'rival', 'river', 'robot', 'roman', 'rough',
  'round', 'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score', 'sense', 'serve',
  'seven', 'shade', 'shake', 'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell',
  'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sight', 'silly', 'since',
  'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile', 'smith',
  'smoke', 'snake', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak',
  'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand',
  'start', 'state', 'steam', 'steel', 'steep', 'stick', 'stiff', 'still', 'stock', 'stone',
  'stood', 'store', 'storm', 'story', 'strip', 'study', 'stuff', 'style', 'sugar', 'suite',
  'super', 'sweet', 'table', 'taken', 'talks', 'taste', 'taxes', 'teach', 'teeth', 'thank',
  'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those', 'three', 'threw',
  'throw', 'tight', 'timer', 'tired', 'title', 'today', 'token', 'tooth', 'topic', 'total',
  'touch', 'tough', 'tower', 'track', 'trade', 'train', 'treat', 'trend', 'trial', 'tribe',
  'trick', 'tried', 'tries', 'truck', 'truly', 'trust', 'truth', 'twice', 'under', 'undue',
  'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value',
  'video', 'virus', 'visit', 'vital', 'vocal', 'voice', 'waste', 'watch', 'water', 'wheel',
  'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'world', 'worry', 'worse',
  'worst', 'worth', 'would', 'wound', 'write', 'wrong', 'wrote', 'yield', 'young', 'youth',
].filter((w) => w.length === 5)

// Comprehensive valid-guess dictionary (~14.8k words), sourced from the public
// Wordle valid-guesses word list. Far larger than WORD_LIST (the curated answer
// pool above) so players can guess any real word, not just possible answers.
export const VALID_GUESSES: Set<string> = new Set([...WORD_LIST, ...(validGuessesData as string[])])
